# -*- coding: utf-8 -*-
"""Untitled66.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw9neM7f5bQig0dKrTe16a4yfpRuo0vy
"""

import pickle, requests, streamlit as st

def fetch_poster(movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US"
    try:
        return "https://image.tmdb.org/t/p/w500/" + requests.get(url).json()['poster_path']
    except (KeyError, requests.exceptions.RequestException):
        return "https://via.placeholder.com/500x750?text=No+Poster"

st.header('Movie Recommender System')
movies = pickle.load(open('Model/movie_list.pkl','rb'))
similarity = pickle.load(open('Model/similarity1.pkl','rb'))

selected_movie = st.selectbox("Select a movie", movies['title'].values)

if st.button('Show Recommendation'):
    idx = movies[movies['title'] == selected_movie].index[0]
    distances = sorted(list(enumerate(similarity[idx])), reverse=True, key=lambda x: x[1])[1:6]

    cols = st.columns(5)
    for col, i in zip(cols, distances):
        with col:
            st.text(movies.iloc[i[0]].title)
            st.image(fetch_poster(movies.iloc[i[0]].movie_id))
